name: Generate Snake Game

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate Snake Game
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: chee86j
          outputs: |
            dist/github-contribution-grid-snake.svg
