name: Generate Snake Game

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate Snake Game
        uses: Platane/snk@master
        with:
          github_user_name: chee86j
          svg_out_path: dist/github-contribution-grid-snake.svg
