name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Generate standard snake game
      - uses: Platane/snk@master
        with:
          github_user_name: chee86j
          svg_out_path: dist/github-snake.svg
